### PR TITLE
remove non-reproducible Implementation-Build-Date

### PR DESCRIPTION
**Pull request by hboutemy**
see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/fasterxml/jackson/annotations/jackson-annotations-2.14.0-rc1.diffoscope

### CODE REVIEW

**Comment by cowtowncoder** [comment]
So these need to be removed since they break RB?

Do you think there is any downside? Is there equivalent metadata to indicate build time, or is that just... unavoidable loss? I don't know if tooling cares about that, and I guess artifacts still have external timestamps.

**Comment by cowtowncoder** [comment]
I guess it's fine, how about I'll just merge this.

**Comment by cowtowncoder** [comment]
@hboutemy I think that Reproducible build somehow caused this:

https://github.com/FasterXML/jackson-databind/issues/3680

which is peculiar in that all class files do have consistent timestamp, but one that is neither one specified in Maven property NOR epoch (but 10 years later). WDYT?

**Comment by cowtowncoder** [comment]
This sounds quite familiar: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2517

**Comment by hboutemy** [comment]
I answered on https://github.com/FasterXML/jackson-databind/issues/3680

**Pull request merged**
