### PR TITLE
Use error-prone compiler

### PR DESCRIPTION
**Pull request by leventov**

### CODE REVIEW

**Comment by leventov** [comment]
The intent of this PR is to eventually use error-prone compiler in all Jackson projects.

**Comment by leventov** [comment]
@cowtowncoder could you please comment on this?

**Comment by cowtowncoder** [comment]
I have never heard of this, so description would be necessary. Adding fully empty PRs is not the way to get things done.

**Comment by cowtowncoder** [comment]
With googling I found a project page, so sounds like this might be something similar to FindBugs and similar tools.

If so, I'd be fine with a new target, or running it as part of some profile. But I do not usually care for running it on critical path of regular builds.

**Comment by leventov** [comment]
This tool is designed to be always-on, Java Compiler replacement, to catch problems earlier (on the developer machine). As you can see here: https://github.com/FasterXML/jackson-databind/pull/1974 and here: https://github.com/FasterXML/jackson-core/pull/447 it generated 8 errors and only one of them could be considered "false positive", when `key.compareTo(key)` is deliberately called in tests.

So I see more value in enabling error-prone as the default compiler. If you still want to make it opt-in, I could change this PR to create a profile, but it means that a separate line should be added to the `.travis.yml` of each of the Jackson projects.

**Comment by cowtowncoder** [comment]
Ok let's just leave it out altogether. While it is nice to catch errors I just do not want to complicate build by having yet one more non-standard componetn on the stack.
I appreciate your help, but at this point I do not want to proceed with this change.

**Pull request closed without merging**
