### PR TITLE
Jacoco maven plugin 0.8.7

### PR DESCRIPTION
**Pull request by dinomite**
Fixes issue in jackson-module-kotlin https://github.com/FasterXML/jackson-module-kotlin/commit/be633b16a9748e11f0e24f60479748391b860719

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Sounds good.

**Comment by cowtowncoder** [comment]
Releasing version `42`, will see what to do with jackson-parent (at least will upgrade 2.13/master)

**Comment by dinomite** [comment]
👍 I can do the Kotlin module updates

**Comment by cowtowncoder** [comment]
Sounds good! I published version `42`: the usual way I've done is to upgrade baseline levels for next minor version, and let individual modules do one-off overrides for current patches if that makes sense (and then remove override from the next minor version).
I haven't really had too many issues with Maven plug-in versions so I may overly careful but it has avoided couple of surprises during releases -- something like missing javadocs or source bundles.

**Comment by cowtowncoder** [comment]
Also: I am back from my vacation and have somewhat of a backlog: will try to get smallest things out first. But will go through all items hopefully by end of the week. Also planning to send an update on my thinking of 2.13 (proposing it to be bit of a "small" release)

**Pull request merged**
